categories:

- name: Job finished - Setup error
  tag: setup
  patterns:
  - 'No such file or directory'
  - 'make.*No rule to make target'

- name: Job didn't finished - Server error
  tag: infra
  patterns:
  - .*Fault 404.*
  - .*503 Service Temporarily Unavailable.*
  - .*504 Gateway.*

- name: Job didn't finished - Docker
  tag: infra
  patterns:
  - Job failed.*registry.*
  - "ERROR:.*Docker.*"
  - "ERROR:.*failed to pull image.*"

- name: Job didn't finished - LAVA Bug
  tag: infra-lava
  patterns:
  - "LAVABug:"

- name: Job finished
  tag: test
  patterns:
  - 'make.* Error'

- name: Job didn't finished - LAVA machine got hung
  tag: infra-lava
  patterns:
  - Job failed.*retries.*

- name: Ok
  tag: ok
  patterns:
  - 'bzImage is ready'
  - 'Created .*kselftest.tar.gz'
  - OBJCOPY .*Image
  - Image is ready

- name: Unknown
  tag: unknown
  patterns:
  - ".*"
